# Generated by Django 2.1 on 2018-08-20 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='createTime',
            new_name='createDate',
        ),
    ]
